services:
  mongo:
    image : mongodb/mongodb-community-server
    container_name: mongodb-planovic
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /datadrive/db:/data/db
    ports:
      - 27017:27017
    restart: no
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/planovic
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge